name: Deploy Hugo Site with TinaCMS to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Hugo
        run: sudo snap install hugo

      - name: Install Dependencies
        run: npm ci

      - name: Build TinaCMS
        env:
          TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          TINA_BRANCH: ${{ vars.TINA_BRANCH}}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
